version: "3"
services:
  app:
    build:
      dockerfile: Dockerfile.prod
      context: .
    volumes:
      - ./:/opt/app/api
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    container_name: settlesphere-postgres
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5438:5432"

volumes:
  postgres_data: